# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remote-pychess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.setWindowModality(QtCore.Qt.NonModal)
        Janela.setEnabled(True)
        Janela.resize(1920, 1080)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        Janela.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Janela.setWindowIcon(icon)
        Janela.setAutoFillBackground(False)
        Janela.setStyleSheet("background-color: rgb(45, 47, 48);")
        Janela.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setEnabled(True)
        self.logo.setGeometry(QtCore.QRect(550, -40, 741, 221))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo.setScaledContents(False)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.whites = QtWidgets.QLabel(self.centralwidget)
        self.whites.setGeometry(QtCore.QRect(300, 40, 271, 61))
        self.whites.setStyleSheet("color: white;")
        self.whites.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.whites.setObjectName("whites")
        self.whiteselo = QtWidgets.QLabel(self.centralwidget)
        self.whiteselo.setGeometry(QtCore.QRect(380, 120, 271, 61))
        self.whiteselo.setStyleSheet("color: white;")
        self.whiteselo.setObjectName("whiteselo")
        self.blackselo = QtWidgets.QLabel(self.centralwidget)
        self.blackselo.setGeometry(QtCore.QRect(1290, 120, 271, 61))
        self.blackselo.setStyleSheet("color: white;")
        self.blackselo.setObjectName("blackselo")
        self.blacks = QtWidgets.QLabel(self.centralwidget)
        self.blacks.setGeometry(QtCore.QRect(1290, 40, 271, 61))
        self.blacks.setStyleSheet("color: white;")
        self.blacks.setObjectName("blacks")
        self.whitehorse = QtWidgets.QWidget(self.centralwidget)
        self.whitehorse.setGeometry(QtCore.QRect(250, 20, 61, 81))
        self.whitehorse.setStyleSheet("image: url(img/whitehorse.png);")
        self.whitehorse.setObjectName("whitehorse")
        self.blackhorse = QtWidgets.QWidget(self.centralwidget)
        self.blackhorse.setGeometry(QtCore.QRect(1570, 20, 61, 81))
        self.blackhorse.setStyleSheet("image: url(img/favicon.png);")
        self.blackhorse.setObjectName("blackhorse")
        self.whitespic = QtWidgets.QWidget(self.centralwidget)
        self.whitespic.setGeometry(QtCore.QRect(50, 30, 171, 151))
        self.whitespic.setStyleSheet("image: url(img/profilepic.jpg);")
        self.whitespic.setObjectName("whitespic")
        self.blackspic = QtWidgets.QWidget(self.centralwidget)
        self.blackspic.setGeometry(QtCore.QRect(1650, 30, 171, 151))
        self.blackspic.setStyleSheet("image: url(img/profilepic.jpg);")
        self.blackspic.setObjectName("blackspic")
        self.game = QtWidgets.QWidget(self.centralwidget)
        self.game.setGeometry(QtCore.QRect(500, 220, 861, 731))
        self.game.setStyleSheet("image: url(img/chessboard.png);")
        self.game.setObjectName("game")
        self.blackstime = QtWidgets.QLabel(self.centralwidget)
        self.blackstime.setGeometry(QtCore.QRect(1290, 200, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.blackstime.setFont(font)
        self.blackstime.setStyleSheet("color: white;")
        self.blackstime.setObjectName("blackstime")
        self.whitestime = QtWidgets.QLabel(self.centralwidget)
        self.whitestime.setGeometry(QtCore.QRect(450, 200, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.whitestime.setFont(font)
        self.whitestime.setStyleSheet("color: white;")
        self.whitestime.setObjectName("whitestime")
        Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Remote PyChess"))
        self.whites.setText(_translate("Janela", "<html><head/><body><p><span style=\" font-size:25pt;\">luisalexleite</span></p></body></html>"))
        self.whiteselo.setText(_translate("Janela", "<html><head/><body><p><span style=\" font-size:36pt;\">ELO: 800</span></p></body></html>"))
        self.blackselo.setText(_translate("Janela", "<html><head/><body><p><span style=\" font-size:36pt;\">ELO: 800</span></p></body></html>"))
        self.blacks.setText(_translate("Janela", "<html><head/><body><p><span style=\" font-size:25pt;\">luisalexleite</span></p></body></html>"))
        self.blackstime.setText(_translate("Janela", "<html><head/><body><p>00:00</p></body></html>"))
        self.whitestime.setText(_translate("Janela", "<html><head/><body><p>00:00</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.showFullScreen()
    sys.exit(app.exec_())